export const data = [
  {
    country: "Afghanistan",
    percentage: 0.3,
    content: "Increase in the production of wheat",
    currency: "AFN",
    symbol: "؋",
    rate: 68.4,
  },
  {
    country: "Algeria",
    percentage: 2,
    content: "Increase in agricultural production",
    currency: "DZD",
    symbol: "دج",
    rate: 132.09,
  },
  {
    country: "Angola",
    percentage: 4.2,
    content: "Increase in GDP",
    currency: "AOA",
    symbol: "Kz",
    rate: 951.47,
  },
  {
    country: "Argentina",
    percentage: 1.5,
    content: "Increase in agricultural productivity",
    currency: "ARS",
    symbol: "$",
    rate: 969.5,
  },
  {
    country: "Australia",
    percentage: 5,
    content: "Decrease in aricultural land",
    currency: "AUD",
    symbol: "$",
    rate: 1.45,
  },
  {
    country: "Austria",
    percentage: 4.4,
    content: "Increase in agricultural output",
    currency: "EUR",
    symbol: "€",
  },
  {
    country: "Belgium",
    percentage: 8.6,
    content: "Decrease in production value",
    currency: "EUR",
    symbol: "€",
  },
  {
    country: "Benin",
    percentage: 56,
    content: "Increase in market goods",
    currency: "XOF",
    symbol: "Fr",
  },
  {
    country: "Brazil",
    percentage: 3.2,
    content: "Increase in agricultural productivity",
    currency: "BRL",
    symbol: "R$",
  },
  {
    country: "Cameroon",
    percentage: 3.2,
    content: "Increase in production index",
    currency: "XAF",
    symbol: "Fr",
  },
  {
    country: "Canada",
    percentage: 50,
    content: "Decrease in number of farms",
    currency: "CAD",
    symbol: "$",
  },
  {
    country: "China",
    percentage: 1.8,
    content: "Increase in grain production",
    currency: "CNY",
    symbol: "¥",
  },
  {
    country: "Colombia",
    percentage: 52,
    content: "Increase in informal land tenure",
    currency: "COP",
    symbol: "$",
  },
  {
    country: "Egypt",
    percentage: 91,
    content: "Increase in GDP",
    currency: "EGP",
    symbol: "ج.م",
  },
  {
    country: "France",
    percentage: 16,
    content: "Decrease in produce price",
    currency: "EUR",
    symbol: "€",
  },
  {
    country: "Germany",
    percentage: 9.2,
    content: "Decrease in economic assessment",
    currency: "EUR",
    symbol: "€",
  },
  {
    country: "Ghana",
    percentage: 5,
    content: "Decrease in food index",
    currency: "GHS",
    symbol: "₵",
  },
  {
    country: "Hungary",
    percentage: 28,
    content: "Increase in agricultural production",
    currency: "HUF",
    symbol: "Ft",
  },
  {
    country: "India",
    percentage: 3.2,
    content: "Increase in agricultural production",
    currency: "INR",
    symbol: "₹",
  },
  {
    country: "Indonesia",
    percentage: 2,
    content: "Decrease in agricultural workforce",
    currency: "IDR",
    symbol: "Rp",
  },
  {
    country: "Iran",
    percentage: 0.3,
    content: "Increase to the GDP",
    currency: "IRR",
    symbol: "﷼",
  },
  {
    country: "Iraq",
    percentage: 50,
    content: "Decrease in crop yield",
    currency: "IQD",
    symbol: "ع.د",
  },
  {
    country: "Israel",
    percentage: 70,
    content: "Decrease in productivity",
    currency: "ILS",
    symbol: "₪",
  },
  {
    country: "Italy",
    percentage: 2.8,
    content: "Increase in agricultural market",
    currency: "EUR",
    symbol: "€",
  },
  {
    country: "Japan",
    percentage: 30,
    content: "Decrease in the number of farms",
    currency: "JPY",
    symbol: "¥",
  },
  {
    country: "Kenya",
    percentage: 15,
    content: "Increase in sugarcane production",
    currency: "KES",
    symbol: "Sh",
  },
  {
    country: "Madagascar",
    percentage: 77,
    content: "Increase in rural poverty",
    currency: "MGA",
    symbol: "Ar",
  },
  {
    country: "Malaysia",
    percentage: 0.1,
    content: "Increase in agricultural sector",
    currency: "MYR",
    symbol: "RM",
  },
  {
    country: "Mexico",
    percentage: 24,
    content: "Decrease in agricultural productivity",
    currency: "MXN",
    symbol: "$",
  },
  {
    country: "Netherlands",
    percentage: 5,
    content: "Increase in agricultural exports",
    currency: "EUR",
    symbol: "€",
  },
  {
    country: "New Zealand",
    percentage: 91,
    content: "Increase in irrigated land",
    currency: "NZD",
    symbol: "$",
  },
  {
    country: "Niger",
    percentage: 15,
    content: "Increase in agricultural sector",
    currency: "XOF",
    symbol: "Fr",
  },
  {
    country: "Nigeria",
    percentage: 0.2,
    content: "Increase in agricultural sector",
    currency: "NGN",
    symbol: "₦",
  },
  {
    country: "Portugal",
    percentage: 4,
    content: "Increase in crop production",
    currency: "EUR",
    symbol: "€",
  },
  {
    country: "Qatar",
    percentage: 15,
    content: "Decrease in food production",
    currency: "QAR",
    symbol: "ر.ق",
  },
  {
    country: "Russia",
    percentage: 15,
    content: "Increase in agricultural productivity",
    currency: "RUB",
    symbol: "₽",
  },
  {
    country: "Saudi Arabia",
    percentage: 7.8,
    content: "Increase in agricultural sector",
    currency: "SAR",
    symbol: "ر.س",
  },
  {
    country: "Singapore",
    percentage: 10,
    content: "Increase in food production",
    currency: "SGD",
    symbol: "$",
  },
  {
    country: "South Africa",
    percentage: 2,
    content: "Decrease in agricultural productivity",
    currency: "ZAR",
    symbol: "R",
  },
  {
    country: "Spain",
    percentage: 8.1,
    content: "Increase in average production",
    currency: "EUR",
    symbol: "€",
  },
  {
    country: "Thailand",
    percentage: 0.5,
    content: "Increase in middle-aged labor",
    currency: "THB",
    symbol: "฿",
  },
  {
    country: "Togo",
    percentage: 40,
    content: "Increase in post-harvest loss",
    currency: "TGO",
    symbol: "Fr",
  },
  {
    country: "Turkey",
    percentage: 2.7,
    content: "Increase in gross value",
    currency: "TRY",
    symbol: "₺",
  },
  {
    country: "Ukraine",
    percentage: 10,
    content: "Increase in crop production",
    currency: "UAH",
    symbol: "₴",
  },
  {
    country: "United Arab Emirates",
    percentage: 2.4,
    content: "Increase in crop production",
    currency: "AED",
    symbol: "د.إ",
  },
  {
    country: "United Kingdom",
    percentage: 18.4,
    content: "Decrease in agricultural productivity",
    currency: "GBP",
    symbol: "£",
  },
  {
    country: "United States",
    percentage: 1.5,
    content: "Increase in farm output",
    currency: "USD",
    symbol: "$",
    basicPrice: 162,
    premiumPrice: 3642,
  },
];
