export const data = [
  {
    country: "Afghanistan",
    percentage: 0.3,
    content: "Increase in the production of wheat",
    currency: "AFN",
    symbol: "؋",
    rate: 68.4,
  },
  {
    country: "Algeria",
    percentage: 2,
    content: "Increase in agricultural production",
    currency: "DZD",
    symbol: "دج",
    rate: 132.09,
  },
  {
    country: "Angola",
    percentage: 4.2,
    content: "Increase in GDP",
    currency: "AOA",
    symbol: "Kz",
    rate: 951.47,
  },
  {
    country: "Argentina",
    percentage: 1.5,
    content: "Increase in agricultural productivity",
    currency: "ARS",
    symbol: "$",
    rate: 969.5,
  },
  {
    country: "Australia",
    percentage: 5,
    content: "Decrease in aricultural land",
    currency: "AUD",
    symbol: "$",
    rate: 1.45,
  },
  {
    country: "Austria",
    percentage: 4.4,
    content: "Increase in agricultural output",
    currency: "EUR",
    symbol: "€",
    rate: 0.91,
  },
  {
    country: "Belgium",
    percentage: 8.6,
    content: "Decrease in production value",
    currency: "EUR",
    symbol: "€",
    rate: 0.91,
  },
  {
    country: "Benin",
    percentage: 56,
    content: "Increase in market goods",
    currency: "XOF",
    symbol: "Fr",
    rate: 591,
  },
  {
    country: "Brazil",
    percentage: 3.2,
    content: "Increase in agricultural productivity",
    currency: "BRL",
    symbol: "R$",
    rate: 5.46,
  },
  {
    country: "Cameroon",
    percentage: 3.2,
    content: "Increase in production index",
    currency: "XAF",
    symbol: "Fr",
    rate: 598.5,
  },
  {
    country: "Canada",
    percentage: 50,
    content: "Decrease in number of farms",
    currency: "CAD",
    symbol: "$",
    rate: 1.36,
  },
  {
    country: "China",
    percentage: 1.8,
    content: "Increase in grain production",
    currency: "CNY",
    symbol: "¥",
    rate: 7.02,
  },
  {
    country: "Colombia",
    percentage: 52,
    content: "Increase in informal land tenure",
    currency: "COP",
    symbol: "$",
    rate: 4165.64,
  },
  {
    country: "Dubai",
    percentage: 20,
    content: "Increase in oaten import",
    currency: "AED",
    symbol: "د.إ",
    rate: 3.67,
  },
  {
    country: "Egypt",
    percentage: 91,
    content: "Increase in GDP",
    currency: "EGP",
    symbol: "ج.م",
    rate: 48.29,
  },
  {
    country: "France",
    percentage: 16,
    content: "Decrease in produce price",
    currency: "EUR",
    symbol: "€",
    rate: 0.91,
  },
  {
    country: "Germany",
    percentage: 9.2,
    content: "Decrease in economic assessment",
    currency: "EUR",
    symbol: "€",
    rate: 0.91,
  },
  {
    country: "Ghana",
    percentage: 5,
    content: "Decrease in food index",
    currency: "GHS",
    symbol: "₵",
    rate: 15.85,
  },
  {
    country: "Hungary",
    percentage: 28,
    content: "Increase in agricultural production",
    currency: "HUF",
    symbol: "Ft",
    rate: 366.17,
  },
  {
    country: "India",
    percentage: 3.2,
    content: "Increase in agricultural production",
    currency: "INR",
    symbol: "₹",
    rate: 15480,
  },
  {
    country: "Indonesia",
    percentage: 2,
    content: "Decrease in agricultural workforce",
    currency: "IDR",
    symbol: "Rp",
    rate: 83.92,
  },
  {
    country: "Iran",
    percentage: 0.3,
    content: "Increase to the GDP",
    currency: "IRR",
    symbol: "﷼",
    rate: 42000,
  },
  {
    country: "Iraq",
    percentage: 50,
    content: "Decrease in crop yield",
    currency: "IQD",
    symbol: "ع.د",
    rate: 1309,
  },
  {
    country: "Israel",
    percentage: 70,
    content: "Decrease in productivity",
    currency: "ILS",
    symbol: "₪",
    rate: 3.81,
  },
  {
    country: "Italy",
    percentage: 2.8,
    content: "Increase in agricultural market",
    currency: "EUR",
    symbol: "€",
    rate: 0.91,
  },
  {
    country: "Japan",
    percentage: 30,
    content: "Decrease in the number of farms",
    currency: "JPY",
    symbol: "¥",
    rate: 148.71,
  },
  {
    country: "Kenya",
    percentage: 15,
    content: "Increase in sugarcane production",
    currency: "KES",
    symbol: "Sh",
    rate: 128.5,
  },
  {
    country: "Madagascar",
    percentage: 77,
    content: "Increase in rural poverty",
    currency: "MGA",
    symbol: "Ar",
    rate: 4556.46,
  },
  {
    country: "Malaysia",
    percentage: 0.1,
    content: "Increase in agricultural sector",
    currency: "MYR",
    symbol: "RM",
    rate: 4.21,
  },
  {
    country: "Mexico",
    percentage: 24,
    content: "Decrease in agricultural productivity",
    currency: "MXN",
    symbol: "$",
    rate: 19.15,
  },
  {
    country: "Netherlands",
    percentage: 5,
    content: "Increase in agricultural exports",
    currency: "EUR",
    symbol: "€",
    rate: 0.91,
  },
  {
    country: "New Zealand",
    percentage: 91,
    content: "Increase in irrigated land",
    currency: "NZD",
    symbol: "$",
    rate: 1.62,
  },
  {
    country: "Niger",
    percentage: 15,
    content: "Increase in agricultural sector",
    currency: "XOF",
    symbol: "Fr",
    rate: 591,
  },
  {
    country: "Nigeria",
    percentage: 0.2,
    content: "Increase in agricultural sector",
    currency: "NGN",
    symbol: "₦",
    rate: 1600,
  },
  {
    country: "Portugal",
    percentage: 4,
    content: "Increase in crop production",
    currency: "EUR",
    symbol: "€",
    rate: 0.91,
  },
  {
    country: "Qatar",
    percentage: 15,
    content: "Decrease in food production",
    currency: "QAR",
    symbol: "ر.ق",
    rate: 3.64,
  },
  {
    country: "Russia",
    percentage: 15,
    content: "Increase in agricultural productivity",
    currency: "RUB",
    symbol: "₽",
    rate: 95.25,
  },
  {
    country: "Saudi Arabia",
    percentage: 7.8,
    content: "Increase in agricultural sector",
    currency: "SAR",
    symbol: "ر.س",
    rate: 3.76,
  },
  {
    country: "Singapore",
    percentage: 10,
    content: "Increase in food production",
    currency: "SGD",
    symbol: "$",
    rate: 1.31,
  },
  {
    country: "South Africa",
    percentage: 2,
    content: "Decrease in agricultural productivity",
    currency: "ZAR",
    symbol: "R",
    rate: 17.48,
  },
  {
    country: "Spain",
    percentage: 8.1,
    content: "Increase in average production",
    currency: "EUR",
    symbol: "€",
    rate: 0.91,
  },
  {
    country: "Thailand",
    percentage: 0.5,
    content: "Increase in middle-aged labor",
    currency: "THB",
    symbol: "฿",
    rate: 33.27,
  },
  {
    country: "Togo",
    percentage: 40,
    content: "Increase in post-harvest loss",
    currency: "TGO",
    symbol: "Fr",
    rate: 591,
  },
  {
    country: "Turkey",
    percentage: 2.7,
    content: "Increase in gross value",
    currency: "TRY",
    symbol: "₺",
    rate: 34.24,
  },
  {
    country: "Ukraine",
    percentage: 10,
    content: "Increase in crop production",
    currency: "UAH",
    symbol: "₴",
    rate: 41.12,
  },
  {
    country: "United Arab Emirates",
    percentage: 2.4,
    content: "Increase in crop production",
    currency: "AED",
    symbol: "د.إ",
    rate: 3.67,
  },
  {
    country: "United Kingdom",
    percentage: 18.4,
    content: "Decrease in agricultural productivity",
    currency: "GBP",
    symbol: "£",
    rate: 0.76,
  },
  {
    country: "United States",
    percentage: 1.5,
    content: "Increase in farm output",
    currency: "USD",
    symbol: "$",
    basicPrice: 162,
    premiumPrice: 3642,
    rate: 1,
  },
];

const universalRate = data.find(
  (country) => country.country === "United States",
)?.basicPrice as any;
const premiumRate = data.find((country) => country.country === "United States")
  ?.premiumPrice as any;
data.forEach((country) => {
  if (country.rate && country.rate !== 0) {
    country.basicPrice = country.rate * universalRate;
  } else {
    console.log("Rate not available for country");
  }
});
data.forEach((country) => {
  if (country.rate && country.rate !== 0) {
    country.premiumPrice = country.rate * premiumRate;
  }
});
